{:ok, socket} = :gen_tcp.connect('127.0.0.1', 25567, [{:active, false},{:packet,2}])
:ok = :gen_tcp.send(socket, "hi\n")
{x, data} = :gen_tcp.recv(socket,0)
IO.puts(data)
:ok = :gen_tcp.send(socket, "hi\n")
{x, data} = :gen_tcp.recv(socket,0)
IO.puts(data)
:ok = :gen_tcp.send(socket, "hi\n")
{x, data} = :gen_tcp.recv(socket,0)
IO.puts(data)
:ok = :gen_tcp.send(socket, "hi\n")
{x, data} = :gen_tcp.recv(socket,0)
IO.puts(data)
:ok = :gen_tcp.send(socket, "hi\n")
{x, data} = :gen_tcp.recv(socket,0)
IO.puts(data)
:gen_tcp.close(socket)
